---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Jonny.
--- DateTime: 2019/1/16 23:07
---


local meta = {}

function meta:test()
    local pb = require "pb"
    local protoc = require "protoc"

    protoc.paths[#protoc+1] = CS.UnityEngine.Application.streamingAssetsPath.."/pb"
    protoc.include_imports = true

--    local p =  CS.UnityEngine.Application.streamingAssetsPath.."/pb/person.pb"
--    assert(pb.loadfile(p))
    
--    local p = "person.proto.txt"
--    assert(protoc:loadfile(p))
  
    assert(protoc:load([[
    message Phone {
      optional string name        = 1;
      optional int64  phonenumber = 2;
}
message Person {
     optional string name     = 1;
     optional int32  age      = 2;
     optional string address  = 3;
     repeated Phone  contacts = 4;
}
    
    ]]))
    
    local data = {
        name = "ilse",
        age = 18,
        contacts = {
            { name = "alice", phonenumber = 12312341234 },
            { name = "bob", phonenumber = 45645674567 }
        }
    }

    local bytes = assert(pb.encode("Person", data))
    print(pb.tohex(bytes))

    local data2 = assert(pb.decode("Person", bytes))
    print(require "serpent".block(data2))
end

return meta